### ISSUE TITLE
Missing eProtocolVersion

### ISSUE THREAD

**Issue by dalebrubaker** [hhblaze/SharmIPC#3]
Hi, this looks like a VERY nice package, thank you.
When I install from Nuget, the latest 1.16.0, and try to do the new() in your examples, tiesky.com.SharmIpc.eProtocolVersion is not recognized and gives a compile error. When I instead reference your SharmIpc.dll directly (SharmIpc462, built from git clone) the enum is recognized, no build issues.
Best regards,
Dale

**Comment by hhblaze** [comment]
Hi, the version 1.17 with protocol versions is not yet available. That's why please use version from Nuget,
instantiating SharmIPC without parameter protocolVersion: 
this 
sm = new tiesky.com.SharmIpc("Global/MyNewSharmIpc", this.RemoteCall);
instead of 
sm = new tiesky.com.SharmIpc("Global/MyNewSharmIpc", this.RemoteCall, protocolVersion: tiesky.com.SharmIpc.eProtocolVersion.V2);
